{WIP} Fix inner group by query
MindscapeHQ/druid4net pull request #46
Opened 2024-09-06 05:26 UTC by redJ4y

Description to come

2024-09-08 20:43 UTC, PanosNB approved these changes
LGTM so far

2024-09-09 21:16 UTC, JasenPalmer requested changes
A few (hopefully) small things to check out

2024-09-09 21:16 UTC, JasenPalmer commented on Raygun.Druid4Net.IntegrationTests/Properties/AssemblyInfo.cs
Looks like you could just delete this whole file

2024-09-09 21:16 UTC, JasenPalmer commented on Raygun.Druid4Net.IntegrationTests/Queries/TestQueryBase.cs
> +    private static readonly IConfigurationRoot Configuration = new ConfigurationBuilder()
The indentation has changed to 4 spaces. It should be 2.
It might be worth adding in a `.editorconfig` file to set the indentation

2024-09-09 21:16 UTC, JasenPalmer commented on Raygun.Druid4Net.Tests/Properties/AssemblyInfo.cs
Also looks like this file can be deleted

2024-09-09 21:16 UTC, JasenPalmer commented on Raygun.Druid4Net.IntegrationTests/Raygun.Druid4Net.IntegrationTests.csproj
> +    <PackageReference Include="Jil" Version="2.15.4" />
This package and `sigil` do not appear to be maintained anymore. I think you should look at removing them

2024-09-09 23:17 UTC, JasenPalmer approved these changes
Looking good. Thanks for the changes and adding that integration test

2024-09-09 23:19 UTC, merged